---
- name: Get group revision values
  hosts: nsx-t
  connection: local
  gather_facts: false
  
  tasks:
  - name: Get groups 
    uri:
      url: https://10.200.12.52/api/v1/infra/domains/default/groups
      user: "{{ username }}"
      password: "{{ password}}"
      method: GET
      force_basic_auth: yes
      validate_certs: false
      status_code: 200
    register: response

  - name: Parse out groups
    set_fact:
      group_list: "{{ response.json.results }}"

  - name:
    set_fact:
      group_rev_dict: "{{ lookup('template', 'group_revision_dict.j2')}}"

  - name: print groups
    debug:
      msg: "{{ group_rev_dict }}"