---
- name: Get tags
  hosts: nsx-t
  connection: local
  gather_facts: false
  
  tasks:
  - name: Get tags from NSX
    uri:
      url: https://10.200.12.52/api/v1/infra/tags
      user: "{{ username }}"
      password: "{{ password}}"
      method: GET
      force_basic_auth: yes
      validate_certs: false
      status_code: 200
    register: response

  - name: print tags
    debug:
      msg: "{{ response.json.results }}"