---
- name: Get groups
  hosts: nsx-t
  connection: local
  gather_facts: false
  
  tasks:
  - name: Get groups 
    uri:
      url: https://10.200.12.52/api/v1/infra/domains/default/groups
      user: "{{ username }}"
      password: "{{ password}}"
      method: GET
      force_basic_auth: yes
      validate_certs: false
      status_code: 200
    register: response

  - name: print groups
    debug:
      msg: "{{ response.json.results }}"