---
nsxtags:
- nsxtag:
   nxsscope: '"ScopeA"'
   nsxtag:  '"TagA"'
   apply_to: 
    resource_type: '"VirtualMachine"'
    resource_ids:
    - 503743c9-e3e8-4872-3a28-f0316166b596
    - 5037db93-80de-95fa-166b-9b361b45ca53
   remove_from: 
    resource_type: '"VirtualMachine"'
    resource_ids:
    - 503743c9-e3e8-4872-3a28-f0316166b596
    - 5037db93-80de-95fa-166b-9b361b45ca53
- nsxtag:
   nxsscope: '"ScopeB"'
   nsxtag:  '"TagB"'
   apply_to: 
    resource_type: '"VirtualMachine"'
    resource_ids:
    - 503743c9-e3e8-4872-3a28-f0316166b596
    - 5037db93-80de-95fa-166b-9b361b45ca53
   remove_from: 
    resource_type: '"VirtualMachine"'
    resource_ids:
    - 503743c9-e3e8-4872-3a28-f0316166b596
    - 5037db93-80de-95fa-166b-9b361b45ca53

NSXGroups:
- display_name: '"Test_Group_Basic"'
  resource_type: '"Group"'
  value: '"Web"'
  key: '"Name"'
  operator: '"CONTAINS"'
  description: '"IAC Test Group. Basic group with no expression, only tags."'
  grp_tags:
  - grp_tag: '"Milky Way"'
    grp_scope: '"Galaxies"'
  - grp_tag: '"Earth"'
    grp_scope: '"Planets"' 
- display_name: '"Test_Group_Path"'
  resource_type: '"Group"'
  value: '"Web"'
  key: '"Name"'
  operator: '"CONTAINS"'
  description: '"IAC Test Group. Group consisting of other groups. "'
  expression:
    resource_type: '"PathExpression"'
    paths: 
    - '"/infra/domains/default/groups/Applications"'
    key:
    operator:
    value:
    external_ids:
- display_name: '"Test_Group_VMs"'
  resource_type: '"Group"'
  value:
  key:
  operator:
  description: '"IAC Test Group. Group created with a list of VM IDs."'
  expression:
    resource_type: '"ExternalIDExpression"'
    paths:
    key:
    operator:
    value:
    external_ids:
    - '"5037f33d-cc7e-b614-20c8-91d7b65558fa"'
    - '"5037b75e-00e2-c66d-dfb2-ab0658251558"'
    - '"5037ae0b-7ab7-37bc-671f-2409e14e9d93"'
- display_name: '"Test_Group_Nested_Conjunction"'
  resource_type: '"Group"'
  value:
  key:
  operator:
  description: '"IAC Test Group. Group using criteria for membership definition"'
  expression:
    resource_type: '"NestedExpression"'
    paths:
    key:
    operator:
    value:
    external_ids:
  nested_expressions:
  - resource_type: '"Condition"'
    key: '"ComputerName"'
    member_type: '"VirtualMachine"'
    operator: '"CONTAINS"'
    conjunction_operator:
    value: '"web"'
  - resource_type: '"ConjunctionOperator"'
    key:
    member_type:
    operator:
    conjunction_operator: '"AND"'
    value:
  - resource_type: '"Condition"'
    key: '"ComputerName"'
    member_type: '"VirtualMachine"'
    operator: '"CONTAINS"'
    conjunction_operator: '"AND"'
    value: '"app"'
- display_name: '"Test_Group_IPs"'
  resource_type: '"Group"'
  value:
  key:
  operator:
  description: '"IAC Test Group. Group created with a list of IPs."'
  expression:
    resource_type: '"IPAddressExpression"'
    paths:
    key:
    operator:
    value:
    ip_addresses:
    - '"10.10.10.0/25"'
    - '"172.16.0.0/12"'

    
services:
- description: '"Alternate ports for HTTPS"'
  display_name: '"Brian-Alt-HTTPS"'
  service_entries:
  - resource_type: '"L4PortSetServiceEntry"'
    display_name: '"port7443-5"'
    destination_ports:
    - '"7773-7775",'
    source_ports:
    l4_protocol: '"TCP"'
  - resource_type: '"L4PortSetServiceEntry"'
    display_name: '"port8443"'
    destination_ports:
    - '"8443"'
    source_ports:
    l4_protocol: '"TCP"'
  - resource_type: '"L4PortSetServiceEntry"'
    display_name: '"port4443"'
    destination_ports:
    - '"4443"'
    source_ports:
    l4_protocol: '"TCP"'
  nested_service_entries:
- description: '"Alternate ports for HTTP"'
  display_name: '"Brian-Alt-HTTP"'
  service_entries:
  - resource_type: '"L4PortSetServiceEntry"'
    display_name: '"port8080_8081"'
    destination_ports:
    - '"8080",'
    - '"8081",'
    source_ports:
    l4_protocol: '"TCP"' 
  nested_service_entries:
- description: '"Random Ports for testing"'
  display_name: '"Brian-Random"'
  service_entries:
  - resource_type: '"L4PortSetServiceEntry"'
    display_name: '"random-ports"'
    destination_ports:
    - '"9099",'
    - '"6066",'
    source_ports:
    l4_protocol: '"UDP"' 
  nested_service_entries:
- description: '"Nested Service Testing"'
  display_name: '"BrianNestedService"'
  service_entries:
  nested_service_entries:
  - resource_type: '"NestedServiceServiceEntry"'
    display_name: '"Brian-Alt-HTTPS"'
    nested_service_path: '"/infra/services/Brian-Alt-HTTPS"'
  - resource_type: '"NestedServiceServiceEntry"'
    display_name: '"Brian-Alt-HTTP"'
    nested_service_path: '"/infra/services/Brian-Alt-HTTP"'
  - resource_type: '"NestedServiceServiceEntry"'
    display_name: '"Brian-Random"'
    nested_service_path: '"/infra/services/Brian-Random"'